# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: asanchez@i3m.upv.es
author_name: Antonio Sanchez
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: apricot
mimetype: ''
mimetype_name: ''
project_short_description: A ri cot.
python_name: apricot
repository: https://github.com/AntonioSanch3z/apricotLab
test: false
viewer_name: ''

